CREATE TABLE Users (
  UserId BIGINT PRIMARY KEY IDENTITY,
  Username VARCHAR(20) NOT NULL UNIQUE,
  Role CHAR(1) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  CreatedOn DATETIME NOT NULL DEFAULT SYSDATETIME(),
  LastLogin DATETIME NULL,
  LoginAttempts INT NOT NULL DEFAULT 0,
)